services:
  postgres:
    image: postgres:15-alpine
    container_name: shared-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - internal

volumes:
  pg_data:

networks:
  internal:
    driver: bridge
