services:
  app:
    container_name: nest-app-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - ${PORT}:${PORT}
    environment:
      NODE_ENV: development
      PORT: ${PORT}
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - internal
    env_file:
      - .env.dev

  postgres:
    image: postgres:15-alpine
    container_name: db-dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - internal

volumes:
  pg_data:

networks:
  internal:
    driver: bridge
