version: '3.8'

services:
  app:
    container_name: nest-app
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - ${PORT}:${PORT}
    environment:
      NODE_ENV: production
      PORT: ${PORT}
    depends_on:
      - postgres
    networks:
      - internal
    env_file:
      - .env.prod

  postgres:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - internal

volumes:
  pg_data:

networks:
  internal:
    driver: bridge
